name: Pull Request Checks

on:
  pull_request:
    branches: ["main"]

jobs:
  checks:
    name: Lint, Type-Check & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: |
          python3 -m pip install --upgrade pip
          pip install poetry
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Configure Poetry
        run: poetry config virtualenvs.in-project true

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Lint with Ruff
        run: poetry run ruff check .

      - name: Type check with MyPy
        run: poetry run mypy src/

      - name: Run tests
        run: poetry run pytest -v
